src/Vagant.Web/Models/Event/BaseEventViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Vagant.Web.Models.Location;

namespace Vagant.Web.Models.Event
{
    public class BaseEventViewModel : BaseViewModel
    {
        public BaseEventViewModel()
        {
            EventInstruments = new EventInstrumentsViewModel();
            Location = new LocationViewModel();
        }

        #region Properties

        public int EventId { get; set; }

        [Required]
        public string Title { get; set; }

        [DisplayName("Start Time")]
        [Required]
        public DateTime StartTime { get; set; }

        [DisplayName("End Time")]
        public DateTime? EndTime { get; set; }

        [DisplayName("Brief Description")]
        [Required]
        public string BriefDescription { get; set; }

        [DisplayName("Full Description")]
        [Required]
        public string FullDescription { get; set; }

        public int? LogoId { get; set; }

        public int? AudioId { get; set; }

        [DisplayName("Instruments")]
        public EventInstrumentsViewModel EventInstruments { get; set; }

        public LocationViewModel Location { get; set; }

        #endregion
    }
}

src/Vagant.Web/Models/Event/EditEventViewModel.cs
namespace Vagant.Web.Models.Event
{
    public class EditEventViewModel : BaseEventViewModel
    {
    }
}

src/Vagant.Web/Models/Event/EventInstrumentsViewModel.cs
namespace Vagant.Web.Models.Event
{
    public class EventInstrumentsViewModel
    {
        public bool IsGuitarUsed { get; set; }

        public bool IsViolinUsed { get; set; }

        public bool IsVocalApplicable { get; set; }

        public bool IsSaxophoneUsed { get; set; }
    }
}

src/Vagant.Web/Controllers/EventController.cs
using Agile.Web.Framework.ActionResults;
using Microsoft.AspNet.Identity;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vagant.Domain.Entities;
using Vagant.Domain.Models;
using Vagant.Domain.Services;
using Vagant.Web.Extensions;
using Vagant.Web.Models.Event;
using Vagant.Web.Models.Location;

namespace Vagant.Web.Controllers
{
    public class EventController : BaseController
    {
        private readonly IEventService _eventService;
        private readonly IFileDataService _fileDataService;
        private readonly IUserService _userService;

        #region Ctor

        public EventController(
            IEventService eventService,
            IFileDataService fileDataService,
            IUserService userService)
        {
            _eventService = eventService;
            _fileDataService = fileDataService;
            _userService = userService;
        }

        #endregion

        #region Actions

        [Authorize]
        public ActionResult Create()
        {
            try
            {
                var viewModel = GetEmptyEventViewModel();

                return View("CreateEvent", viewModel);
            }
            catch (Exception)
            {
                //todo: log error
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        public ActionResult Clone(int id)
        {
            try
            {
                var @event = _eventService.GetEvent(id);
                var viewModel = GetEditEventViewModel(@event);

                return View("CreateEvent", viewModel);
            }
            catch (Exception)
            {
                //todo: log error
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(EditEventViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("CreateEvent", viewModel);
                }

                int? logoId = viewModel.LogoId;
                int? audioId = viewModel.AudioId;

                var logoFile = GetImageFileFromStream();
                if (logoFile != null && logoFile.ContentLength > 0)
                {
                    logoId = SaveFile(logoFile);
                }

                var audioFile = GetAudioFileFromStream();
                if (audioFile != null && audioFile.ContentLength > 0)
                {
                    audioId = SaveFile(audioFile);
                }

                var id = _eventService.CreateEvent(GetEventModel(viewModel, logoId, audioId));

                return RedirectToAction("Details", "Event", new { id = id });

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //public ActionResult Edit(int id)
        //{
        //    try
        //    {
        //        var viewModel = GetEditableEventViewModel(id);

        //        return View("EditEvent", viewModel);
        //    }
        //    catch (Exception)
        //    {
        //        //todo: log error
        //        return RedirectToAction("Index", "Home");
        //    }
        //}

        public ActionResult Details(int id)
        {
            try
            {
                var viewModel = GetEventDetailsViewModel(id);

                return View(viewModel);
            }
            catch (Exception)
            {
                //todo: log error
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult GetEvents(DateTime startDate, DateTime endDate)
        {
            try
            {
                var events = _eventService.GetEvents(startDate, endDate);
                var jsonData = events.GroupBy(x => x.StartTime.Date).Select(d => new
                {
                    eventDate = d.Key.ToShortDateString(),
                    events = d.Select(x => new
                    {
                        eventId = x.Id,
                        logoUrl = x.LogoId.HasValue
                            ? Url.Action("Download", "FileData", new { id = x.LogoId })
                            : Url.Content("~/Content/Images/logo-default.jpg"),
                        audioUrl = x.AudioId.HasValue ? Url.Action("Download", "FileData", new { id = x.AudioId }) : null,
                        title = x.Title,
                        rate = x.Rate,
                        instruments = new
                        {
                            isGuitarUsed = x.IsGuitarUsed,
                            isViolinUsed = x.IsViolinUsed,
                            isVocalApplicable = x.IsVocalApplicable,
                            isSaxophoneUsed = x.IsSaxophoneUsed
                        }
                    })
                });

                return new SuccessJsonResult(jsonData);
            }
            catch (Exception)
            {
                return new HttpBadRequestResult();
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddComment(int eventId, string text)
        {
            try
            {
                var comment = new EventComment
                {
                    EventId = eventId,
                    Text = text,
                    UserId = UserId
                };
                _eventService.CreateComment(comment);
                return new SuccessJsonResult();
            }
            catch (Exception)
            {
                //todo: log error
                return new HttpBadRequestResult();
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateRating(int eventId, double rating)
        {
            try
            {
                var newRating = _eventService.UpdateRating(UserId, eventId, rating);
                return new SuccessJsonResult(newRating);
            }
            catch (Exception)
            {
                //todo: log error
                return new HttpBadRequestResult();
            }
        }

        #endregion

        #region Private Methods

        private EditEventViewModel GetEmptyEventViewModel()
        {
            var result = new EditEventViewModel()
            {
                StartTime = DateTime.Now
            };

            return result;
        }

        //private EditEventViewModel GetEditableEventViewModel(int eventId)
        //{
        //    var result = new EditEventViewModel();

        //    //todo: get data from service

        //    return result;
        //}

        private EventDetailsViewModel GetEventDetailsViewModel(int eventId)
        {
            var eventModel = _eventService.GetEvent(eventId);
            return GetEventDetailsViewModel(eventModel);
        }

        #region Logo

        private int? SaveFile(HttpPostedFileBase file)
        {
            var imageFile = new FileData
            {
                Data = ReadToEnd(file.InputStream),
                ContentType = file.ContentType
            };

            _fileDataService.Create(imageFile);
            return imageFile.Id;
        }

        private HttpPostedFileBase GetImageFileFromStream()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files["logo"];
                if (file.IsImage())
                {
                    return file;
                }
            }

            return null;
        }

        private HttpPostedFileBase GetAudioFileFromStream()
        {
            if (Request.Files.Count > 0)
            {
                return Request.Files["audio"];
            }

            return null;
        }

        private byte[] ReadToEnd(Stream stream)
        {
            long originalPosition = 0;

            if (stream.CanSeek)
            {
                originalPosition = stream.Position;
                stream.Position = 0;
            }

            try
            {
                var readBuffer = new byte[4096];

                int totalBytesRead = 0;
                int bytesRead;

                while ((bytesRead = stream.Read(readBuffer, totalBytesRead, readBuffer.Length - totalBytesRead)) > 0)
                {
                    totalBytesRead += bytesRead;

                    if (totalBytesRead == readBuffer.Length)
                    {
                        int nextByte = stream.ReadByte();
                        if (nextByte != -1)
                        {
                            var temp = new byte[readBuffer.Length * 2];
                            Buffer.BlockCopy(readBuffer, 0, temp, 0, readBuffer.Length);
                            Buffer.SetByte(temp, totalBytesRead, (byte)nextByte);
                            readBuffer = temp;
                            totalBytesRead++;
                        }
                    }
                }

                byte[] buffer = readBuffer;
                if (readBuffer.Length != totalBytesRead)
                {
                    buffer = new byte[totalBytesRead];
                    Buffer.BlockCopy(readBuffer, 0, buffer, 0, totalBytesRead);
                }
                return buffer;
            }
            finally
            {
                if (stream.CanSeek)
                {
                    stream.Position = originalPosition;
                }
            }
        }

        #endregion

        private EventModel GetEventModel(EditEventViewModel viewModel, int? logoId, int? audioId)
        {
            return new EventModel
            {
                AuthorId = User.Identity.GetUserId(),
                BriefDescription = viewModel.BriefDescription,
                StartTime = viewModel.StartTime,
                EndTime = viewModel.EndTime,

src/Vagant.Web/Controllers/FileDataController.cs
using Agile.Web.Framework.ActionResults;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Vagant.Domain.Entities;
using Vagant.Domain.Services;

namespace Vagant.Web.Controllers
{
    public class FileDataController : Controller
    {
        #region Fields

        private readonly IFileDataService _fileDataService;

        #endregion

        #region Ctor

        public FileDataController(IFileDataService fileDataService)
        {
            _fileDataService = fileDataService;
        }

        #endregion

        #region Actions

        [HttpPost]
        public ActionResult Upload()
        {
            try
            {
                var file = GetFileFromStream();

                var fileData = new FileData
                {
                    Data = ReadToEnd(file.InputStream),
                    ContentType = file.ContentType
                };

                _fileDataService.Create(fileData);

                return new SuccessJsonResult(fileData.Id);
            }
            catch (Exception)
            {
                return new HttpBadRequestResult();
            }
        }

        [HttpGet]
        public ActionResult Download(int id)
        {
            var context = HttpContext;
            try
            {
                var fileData = _fileDataService.Get(id);

                if (fileData == null)
                {
                    return new HttpNotFoundResult();
                }

                return File(fileData.Data, fileData.ContentType);
            }
            catch (Exception)
            {
                //log error
                return new HttpBadRequestResult();
            }
        }

        #endregion

        #region Helper Methods

        private HttpPostedFileBase GetFileFromStream()
        {
            if (Request.Files.Count > 0)
            {
                return Request.Files[0];
            }

            return null;
        }

        private byte[] ReadToEnd(Stream stream)
        {
            long originalPosition = 0;

            if (stream.CanSeek)
            {
                originalPosition = stream.Position;
                stream.Position = 0;
            }

            try
            {
                var readBuffer = new byte[4096];

                int totalBytesRead = 0;
                int bytesRead;

                while ((bytesRead = stream.Read(readBuffer, totalBytesRead, readBuffer.Length - totalBytesRead)) > 0)
                {
                    totalBytesRead += bytesRead;

                    if (totalBytesRead == readBuffer.Length)
                    {
                        int nextByte = stream.ReadByte();
                        if (nextByte != -1)
                        {
                            var temp = new byte[readBuffer.Length * 2];
                            Buffer.BlockCopy(readBuffer, 0, temp, 0, readBuffer.Length);
                            Buffer.SetByte(temp, totalBytesRead, (byte)nextByte);
                            readBuffer = temp;
                            totalBytesRead++;
                        }
                    }
                }

                byte[] buffer = readBuffer;
                if (readBuffer.Length != totalBytesRead)
                {
                    buffer = new byte[totalBytesRead];
                    Buffer.BlockCopy(readBuffer, 0, buffer, 0, totalBytesRead);
                }
                return buffer;
            }
            finally
            {
                if (stream.CanSeek)
                {
                    stream.Position = originalPosition;
                }
            }
        }

        #endregion
    }
}

src/Vagant.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Vagant.Domain.Models;
using Vagant.Domain.Services;
using Vagant.Web.Models.Profile;
using Vagant.Web.Models.ProfileHistory;

namespace Vagant.Web.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly IEventService _eventService;
        private readonly IUserService _userService;

        #region Ctor

        public ProfileController(IEventService eventService,
            IUserService userService)
        {
            _eventService = eventService;
            _userService = userService;
        }

        #endregion

        #region Actions

        [HttpGet]
        [Authorize]
        public ActionResult Details(string userId)
        {
            try
            {
                var userEvents = _eventService.GetUserEvents(userId);
                var viewModel = GetProfileDetailsViewModel(userId, userEvents);
                return View(viewModel);
            }
            catch (Exception)
            {
                //todo: log error
                return RedirectToAction("Index", "Home");
            }
        }

        #endregion

        #region Private Methods

        private ProfileDetailsViewModel GetProfileDetailsViewModel(string userId, IList<EventModel> userEvents)
        {
            var user = _userService.GetById(userId);

            var result = new ProfileDetailsViewModel()
            {
                UserName = string.Format("{0} {1}", user.FirstName, user.LastName)
            };

            result.HistoryItems = userEvents
                                    .OrderBy(x => x.StartTime)
                                    .Select(GetProfileHistoryItemViewModel).ToList();

            return result;
        }

        private ProfileHistoryItemViewModel GetProfileHistoryItemViewModel(EventModel model)
        {
            return new ProfileHistoryItemViewModel
            {
                EventDate = model.StartTime,
                EventName = model.Title,
                EventId = model.Id,
                EventRate = model.Rate,
                CanClone = model.AuthorId == UserId
            };
        }

        #endregion
    }
}

src/Vagant.Web/Views/Event/CreateEvent.cshtml
@model Vagant.Web.Models.Event.EditEventViewModel

@{
    ViewBag.Title = "Event Creating";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    @Styles.Render("~/bundles/css/CreateEvent")
}

@section BodyScripts {
    @Scripts.Render("~/bundles/CreateEvent")
}

<div class="page event-page">
    <div class="event-body">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <section id="createEvent">
                    @using (Html.BeginForm("Create", "Event", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        @Html.HiddenFor(m => m.LogoId)
                        @Html.HiddenFor(m => m.AudioId)
                        <div class="form-group">
                            @Html.LabelFor(m => m.Title, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.BriefDescription, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.BriefDescription, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.FullDescription, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextAreaFor(m => m.FullDescription, new { @class = "form-control", rows = "10" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.StartTime, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.StartTime, new { @class = "form-control datetimepicker" })
                            </div>
                        </div>
                        @*<div class="form-group">
                            @Html.LabelFor(m => m.EndTime, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.EndTime, new { @class = "form-control datetimepicker" })
                            </div>
                        </div>*@
                        <div class="form-group">
                            @Html.LabelFor(m => m.EventInstruments, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                @Html.CheckBoxFor(m => m.EventInstruments.IsGuitarUsed) Guitar
                                <br/>
                                @Html.CheckBoxFor(m => m.EventInstruments.IsViolinUsed) Violin
                                <br />
                                @Html.CheckBoxFor(m => m.EventInstruments.IsSaxophoneUsed) Saxophone
                                <br />
                                @Html.CheckBoxFor(m => m.EventInstruments.IsVocalApplicable) Vocal
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Logo</label>
                            <div class="col-md-9">
                                <input type="file" name="logo" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Audio</label>
                            <div class="col-md-9">
                                <input type="file" name="audio" />
                            </div>
                        </div>
                        @Html.HiddenFor(m => m.Location.Latitude, new { @class = "form-control", @id = "latitude" })
                        @Html.HiddenFor(m => m.Location.Longitude, new { @class = "form-control", id = "longitude" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.Location, new { @class = "col-md-3 control-label" })
                            <div class="col-md-9">
                                <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
                                <div style='overflow:hidden;height:440px;'>
                                    <div id='gmap_canvas' style='height:440px;'></div>
                                    @*<style>
                                        #gmap_canvas img {
                                            max-width: none !important;
                                            background: none !important;
                                        }
                                    </style>*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </section>
            </div>
        </div>
    </div>
</div>

src/Vagant.Web/Views/Event/Details.cshtml
@model Vagant.Web.Models.Event.EventDetailsViewModel

@{
    ViewBag.Title = "Event Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    @Styles.Render("~/bundles/css/StarRating")
    @Styles.Render("~/bundles/css/Event")
}

@section BodyScripts {
    @Scripts.Render("~/bundles/StarRating")
    @Scripts.Render("~/bundles/DetailsEvent")
    @Scripts.Render("~/bundles/Event")
}

<script type="text/javascript">
    var vagantApp = window.vagantApp || {};
    vagantApp.event = vagantApp.event || {};

    vagantApp.event.rate = '@Model.Rate';
    vagantApp.event.isRatingEditable = '@Model.IsRatingEditable.ToString().ToLower()';
    vagantApp.event.updateRatingUrl = '@Url.Action("UpdateRating", "Event")';
    vagantApp.event.eventId = '@Model.EventId'
</script>

<div class="page event-page">
    <div class="event-body event-details-body">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 form-horizontal">
                <div class="row">
                    <div class="col-md-5">
                        @if (Model.LogoId.HasValue)
                        {
                            <img class="logo-image" src="@Url.Action("Download", "FileData", new { id = Model.LogoId })" />
                        }
                        else
                        {
                            <img class="logo-image" src="@Url.Content("~/Content/Images/logo-default.jpg")" />
                        }
                    </div>
                    <div class="col-md-7">
                        <div class="title">
                            @Html.DisplayFor(m => m.Title)
                        </div>
                        <div class="space"></div>
                        <div class="brief-description">
                            @Html.DisplayFor(m => m.BriefDescription)
                        </div>
                        <div class="space"></div>
                        <div class="author">
                            Author: <a href="@Url.Action("Details", "Profile", new { userId = Model.AuthorId })">@Html.DisplayFor(m => m.AuthorName)</a>
                        </div>
                        <div class="space"></div>
                        <div class="start-time">
                            Event Date: @Html.DisplayFor(m => m.StartTime)
                        </div>
                        <div class="space"></div>
                        <div class="instruments">
                            @Html.CheckBoxFor(m => m.EventInstruments.IsGuitarUsed, new { @disabled = "disabled" }) Guitar
                            @Html.CheckBoxFor(m => m.EventInstruments.IsViolinUsed, new { @disabled = "disabled" }) Violin
                            @Html.CheckBoxFor(m => m.EventInstruments.IsSaxophoneUsed, new { @disabled = "disabled" }) Saxophone
                            @Html.CheckBoxFor(m => m.EventInstruments.IsVocalApplicable, new { @disabled = "disabled" }) Vocal
                        </div>
                        @if (Model.AudioId.HasValue)
                        {
                            <div class="space"></div>
                            <div class="row">
                                <audio controls>
                                    <source src="@Url.Action("Download", "FileData", new { id = Model.AudioId })">
                                    Your browser does not support the audio element.
                                </audio>
                            </div>
                        }
                    </div>
                </div>
                <hr/>
                <div class="row full-description">
                    @Html.DisplayFor(m => m.FullDescription)
                </div>
                <div class="space"></div>
                <div class="row">
                    @Html.HiddenFor(m => m.Location.Latitude, new { @id = "latitude" })
                    @Html.HiddenFor(m => m.Location.Longitude, new { @id = "longitude" })
                    <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
                    <div style='overflow:hidden;height:440px;'>
                        <div id='gmap_canvas' style='height:440px;'></div>
                        <style>
                            #gmap_canvas img {
                                max-width: none !important;
                                background: none !important;
                            }
                        </style>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="rating-container" data-bind="template: { name: 'starRatingTemplate', data: rating }">
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("Event/_StarRating")

src/Vagant.Web/Views/Event/EditEvent.cshtml
@model Vagant.Web.Models.Event.EditEventViewModel

@{
    ViewBag.Title = "Event Editing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    @Styles.Render("~/bundles/css/Event")
}

@section BodyScripts {
    @Scripts.Render("~/bundles/Event")
}

<div class="page event-page">
    <div class="event-header">
        <div class="event-image-container">
            <img class="profile-image" src="" alt="no image" />
        </div>
        <div class="event-main-information">

        </div>
    </div>
    <div class="event-body">

    </div>
</div>